name = "Stipple"
uuid = "4acbeb90-81a0-11ea-1966-bdaff8155998"
authors = ["Adrian <e@essenciary.com>"]
version = "0.25.16"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieSession = "03cc5b98-4f21-4eb6-99f2-22eced81f962"
GenieSessionFileSession = "5c4fdc26-39e3-47cf-9034-e533e09961c2"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Mixers = "2a8e4939-dab8-5edc-8f64-72a8776f13de"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
FilePathsBase = "0.9"
Genie = "5.11"
GenieSession = "1"
GenieSessionFileSession = "1"
JSON3 = "1.9"
MacroTools = "0.5"
Mixers = "0.1.2"
Observables = "0.3, 0.4, 0.5"
OrderedCollections = "1"
Parameters = "0.12"
Reexport = "1"
Requires = "1"
StructTypes = "1.8"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
