name = "Stipple"
uuid = "4acbeb90-81a0-11ea-1966-bdaff8155998"
authors = ["Adrian <e@essenciary.com>"]
version = "0.10.0"

[deps]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
FilePathsBase = "0.9"
Genie = "1"
JSON = "0.21"
Observables = "0.3, 0.4"
Reexport = "0.2, 1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
